pr0nauto ignores stitch failures after pr0nstitch.  Now that pre-optimizer is pretty good, its almost always the right thing to do

diff --git a/stitch/pr0nauto b/stitch/pr0nauto
--- a/stitch/pr0nauto
+++ b/stitch/pr0nauto
@@ -15,15 +15,18 @@ if cat stitch_failures.json |grep '"critical_images": 0'
 then
     echo 'No stitch failures'
 else
-	echo 'Failures, autopilot done'
-	exit 1
+	echo 'WARNING: failure'
+	# used to exit when missing images was a bigger deal
+	# now that using (quick) pre-optimizer might as well
+	# make a best effort
+	#exit 1
 fi
 
 echo
 echo
 echo '**********************************'
 echo 'No failures, optimizing'
-time pr0npto --pre-opt out.pto ||exit 1
+time pr0npto --pre-opt out.pto
 
 # fit to screen
 time pano_modify --fov=AUTO --canvas=AUTO -o out.pto out.pto
@@ -31,7 +34,7 @@ time pano_modify --fov=AUTO --canvas=AUTO -o out.pto out.pto
 echo
 echo
 echo 'Done!  Open with Hugin to adjust size and rotate'
-) || exit 1
+)
 
-pr0nhugin out.pto &
+pr0nhugin out.pto
 
